import "package:json_annotation/json_annotation.dart";
part 'category.g.dart';
@JsonSerializable()
class Autogenerated {
  int s;
  String m;
  D d;

  Autogenerated({this.s, this.m, this.d});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    s = json['s'];
    m = json['m'];
    d = json['d'] != null ? new D.fromJson(json['d']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['s'] = this.s;
    data['m'] = this.m;
    if (this.d != null) {
      data['d'] = this.d.toJson();
    }
    return data;
  }
}

class D {
  List<CategoryList> categoryList;
  int total;

  D({this.categoryList, this.total});

  D.fromJson(Map<String, dynamic> json) {
    if (json['categoryList'] != null) {
      categoryList = new List<CategoryList>();
      json['categoryList'].forEach((v) {
        categoryList.add(new CategoryList.fromJson(v));
      });
    }
    total = json['total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.categoryList != null) {
      data['categoryList'] = this.categoryList.map((v) => v.toJson()).toList();
    }
    data['total'] = this.total;
    return data;
  }
}

class CategoryList {
  String id;
  String name;
  String title;
  String createdAt;
  String updatedAt;
  String icon;
  String background;
  String tagId;
  String weight;
  bool isSubscribe;

  CategoryList(
      {this.id,
      this.name,
      this.title,
      this.createdAt,
      this.updatedAt,
      this.icon,
      this.background,
      this.tagId,
      this.weight,
      this.isSubscribe});

  CategoryList.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    title = json['title'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    icon = json['icon'];
    background = json['background'];
    tagId = json['tagId'];
    weight = json['weight'];
    isSubscribe = json['isSubscribe'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['title'] = this.title;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['icon'] = this.icon;
    data['background'] = this.background;
    data['tagId'] = this.tagId;
    data['weight'] = this.weight;
    data['isSubscribe'] = this.isSubscribe;
    return data;
  }
}
