// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'category.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Autogenerated _$AutogeneratedFromJson(Map<String, dynamic> json) {
  return Autogenerated(
      s: json['s'] as int,
      m: json['m'] as String,
      d: json['d'] == null
          ? null
          : D.fromJson(json['d'] as Map<String, dynamic>));
}

Map<String, dynamic> _$AutogeneratedToJson(Autogenerated instance) =>
    <String, dynamic>{'s': instance.s, 'm': instance.m, 'd': instance.d};
