import "package:json_annotation/json_annotation.dart";
part 'login.g.dart';
@JsonSerializable()
class Autogenerated {
  String message;
  Data data;
  int code;

  Autogenerated({this.message, this.data, this.code});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    code = json['code'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data.toJson();
    }
    data['code'] = this.code;
    return data;
  }
}

class Data {
  String userID;
  String companyID;
  String personnelID;
  String personnelName;
  String telphone;
  String departMentID;
  String departMentName;
  int sex;
  String manageID;
  String manage;
  String memberToken;
  String loginToken;
  String learnUrl;
  String userCode;

  Data(
      {this.userID,
      this.companyID,
      this.personnelID,
      this.personnelName,
      this.telphone,
      this.departMentID,
      this.departMentName,
      this.sex,
      this.manageID,
      this.manage,
      this.memberToken,
      this.loginToken,
      this.learnUrl,
      this.userCode});

  Data.fromJson(Map<String, dynamic> json) {
    userID = json['UserID'];
    companyID = json['CompanyID'];
    personnelID = json['PersonnelID'];
    personnelName = json['PersonnelName'];
    telphone = json['Telphone'];
    departMentID = json['DepartMentID'];
    departMentName = json['DepartMentName'];
    sex = json['Sex'];
    manageID = json['ManageID'];
    manage = json['Manage'];
    memberToken = json['member_Token'];
    loginToken = json['LoginToken'];
    learnUrl = json['learn_url'];
    userCode = json['UserCode'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['UserID'] = this.userID;
    data['CompanyID'] = this.companyID;
    data['PersonnelID'] = this.personnelID;
    data['PersonnelName'] = this.personnelName;
    data['Telphone'] = this.telphone;
    data['DepartMentID'] = this.departMentID;
    data['DepartMentName'] = this.departMentName;
    data['Sex'] = this.sex;
    data['ManageID'] = this.manageID;
    data['Manage'] = this.manage;
    data['member_Token'] = this.memberToken;
    data['LoginToken'] = this.loginToken;
    data['learn_url'] = this.learnUrl;
    data['UserCode'] = this.userCode;
    return data;
  }
}
