/*
***网络请求封装
***
*/
import 'dart:io';
import 'dart:convert';
import 'package:dio/dio.dart';
import 'package:hk_app/data/authoriz.dart';
import 'package:hk_app/data/login.dart';
import 'package:shared_preferences/shared_preferences.dart';
void httpClient() async {
  var responseBody;
  var httpClient = new HttpClient();
  var request = await httpClient.getUrl(Uri.parse("http://www.wanandroid.com/project/list/1/json?cid=1"));
  var response = await request.close();
  if (response.statusCode == 200){
        responseBody = await response.transform(Utf8Decoder()).join();
        //print(responseBody);
  }
  httpClient.close();
}

// 授权地址
const url = 'http://edi01.ysappstore.com:8012/api/v1/Authoriz/Auth';
var baseUrl= "",memberToken = '',prvComany='';
dynamic roleid;
// Get请求
// Authoriz请求
Future authorizRequest(dataParam) async{
  Dio dio = new Dio();
  /*dataParam = {
    'body':dataParam
  };*/
   //Fiddler抓包设置代理
  (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (client){
    client.findProxy = (url){
      return "PROXY 172.31.61.75:8888";
    };
    //抓Https包设置
    client.badCertificateCallback =
        (X509Certificate cert, String host, int port) => true;
  };
  var content;
  try {
    Response response = await dio.post(url,data:dataParam);
    content = response.data.toString();
  }
  catch (e){
    print(e);
  }
  return new Future((){
     Map<String, dynamic> json = jsonDecode(content);
     var data = AuthrizData.fromJson(json);
     if (data.status.code == 0){
       baseUrl = data.data.httpPort;
       roleid = data.data.roleID;
     }
    return data;
  });
  
}


// Authoriz请求
Future ajaxRequest(dataParam,url) async{
  Dio dio = new Dio();
  //Fiddler抓包设置代理
  (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (client){
    client.findProxy = (url){
      return "PROXY 172.31.61.75:8888";
    };
    //抓Https包设置
    client.badCertificateCallback =
        (X509Certificate cert, String host, int port) => true;
  };
   SharedPreferences.getInstance()
     ..then((prefs) {
        Map<String, dynamic> userinfo = json.decode(prefs.getString("userInfo"));
       if(userinfo !=null){
         memberToken = Autogenerated.fromJson(userinfo).data.memberToken;
         prvComany =Autogenerated.fromJson(userinfo).data.companyID;
        }
     });
  dio.options.headers = {
        "X-HKMobile-ApiKey" :  memberToken,
				"RoleId" : roleid,
				"PrvCompany" : prvComany
  };
  var content;
  var response = await dio.post(baseUrl+url ,data:dataParam);
  content = response.toString();
  return new Future.delayed(Duration(milliseconds: 200 ),() async{
     Map<String, dynamic> json = jsonDecode(content);
     var data = Autogenerated.fromJson(json);
     if (data.code == 1){
        SharedPreferences prefs = await SharedPreferences.getInstance();
        await prefs.setString("userInfo", content);
     }
    return data;
  });
}