import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:hk_app/util/http.dart';
import 'package:hk_app/data/category.dart';
import 'dart:convert';

class ListViews extends StatefulWidget{
  @override
  ListState createState() => ListState();
  
}
class ListState extends State<ListViews>{
    
   List<Tab> tabs = <Tab>[];
  @override
  void initState(){
     getCategories().then((res){
        Map<String, dynamic> json = jsonDecode(res);
        var data = Autogenerated.fromJson(json);
        if (data.m == 'success'){
          dynamic categoryList = data.d.categoryList;
           List<Tab> tabsData = [];
            categoryList.forEach((li){
              tabsData.add(new Tab(
                text: li.name,
              ));
          });
         
            tabs = tabsData;
            print(tabs.toString());
          
         } 
     });
     super.initState();
  }
  Widget build (BuildContext context) {
    return DefaultTabController(
      length: tabs.length,
      child: Scaffold(
        appBar: AppBar(
          title: Text("掘金",style: TextStyle(color: Colors.white)),
          bottom: TabBar(
            tabs: tabs,
            
            isScrollable: true,
          ),
        ),
        body: new TabBarView(
          children: tabs.map((Tab tab){
            return Center(
              child:Text(tab.text)
            );
          }).toList(),
        )
      ),
    );
  }
}
class ListContent extends StatefulWidget {
  @override
  _ListContentState createState() => _ListContentState();
}

class _ListContentState extends State<ListContent> {
  @override
  Widget build(BuildContext context) {
    var listTiles= <Widget>[
      
    ];
    for (var i=0;i<20;i++){
      listTiles.add(
          ListTile(
            leading: Icon(Icons.face),
            title: Text('这第一级标题'),
            subtitle: Text('这是第二级标题'),
          )
      );
      listTiles.add(
          Divider()
      );
    }
    return ListView(children: listTiles);
  }
}


