import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:hk_app/util/http.dart';
import 'package:hk_app/data/category.dart';
import 'dart:convert';

class ListViews extends StatefulWidget{
  @override
  ListState createState() => ListState();
  
}
class ListState extends State<ListViews>{
    
  List tabContent = <Widget>[];
  List tabs = <Tab>[];
  
  @override
  void initState(){
     super.initState();
  }
  void listView(){
  }
  Widget build (BuildContext context) {
    return FutureBuilder(
      future:getCategories(),
      builder: (context ,AsyncSnapshot snapshot){
        print(snapshot.connectionState);
        switch (snapshot.connectionState) {
          case ConnectionState.none: 
          return StateNone();
          break;
          case ConnectionState.waiting: 
          return StateNone();
          break;
          case ConnectionState.done: 
             Map<String, dynamic> json = jsonDecode(snapshot.data);
              var data = Autogenerated.fromJson(json);
              if (data.m == 'success'){
                dynamic categoryList = data.d.categoryList;
                categoryList.forEach((li){
                    tabContent.add(
                      Text(li.name),
                    );
                    tabs.add(new Tab(
                      text: li.name,
                    ));
                });
                return Body(tabs:tabs,tabContent:tabContent);
              } else {
                return StateNone();
              }
            
            break;
          
          case ConnectionState.active:
            // TODO: Handle this case.
            break;
        }
        return null;
        
       
      },
    );
  }
}
// 
class Body extends StatefulWidget {
  final tabs;
  final tabContent;
 @override
  Body({this.tabs,this.tabContent}):super();
  _BodyState createState() => _BodyState();
}

class _BodyState extends State<Body> {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: widget.tabs.length,
      child: Scaffold(
        appBar: AppBar(
          title: Text("掘金",style: TextStyle(color: Colors.white)),
          bottom: TabBar(
            tabs: widget.tabs,
            indicatorSize:TabBarIndicatorSize.label,
            isScrollable: true,
          ),
        ),
        body: new TabBarView(
          children: widget.tabContent,
        )
      ),
    );
  }
}
// 构建未获取数据渲染界面
class StateNone extends StatefulWidget {
  @override
  _StateNoneState createState() => _StateNoneState();
}

class _StateNoneState extends State<StateNone> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('掘金'),
      ),
      body: Center(child: Text('加载中'),),
    );
  }
}
class ListContent extends StatefulWidget {
  @override
  _ListContentState createState() => _ListContentState();
}

class _ListContentState extends State<ListContent> {
  @override
  Widget build(BuildContext context) {
    var listTiles= <Widget>[
      
    ];
    for (var i=0;i<20;i++){
      listTiles.add(
          ListTile(
            leading: Icon(Icons.face),
            title: Text('这第一级标题'),
            subtitle: Text('这是第二级标题'),
          )
      );
      listTiles.add(
          Divider()
      );
    }
    return ListView(children: listTiles);
  }
}


