import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/widgets.dart';
import 'package:hk_app/report/juejing/listContent/backEnd.dart';
import 'package:hk_app/util/http.dart';
import 'package:hk_app/data/category.dart';

import 'dart:convert';
class ListViews extends StatefulWidget{
  @override
  ListState createState() => ListState();
  
}
class ListState extends State<ListViews>{
  dynamic currentIndex = 1;
  List tabContent = <Widget>[];
  List tabs = <Tab>[];
  
  @override
  void initState(){
     super.initState();
  }
  Widget build (BuildContext context) {
    return 
        FutureBuilder(
          future:getCategories(),
          builder: (context ,AsyncSnapshot snapshot){
            //print(snapshot.data.toString());
            switch (snapshot.connectionState) {
              case ConnectionState.none: 
              return StateNone();
              break;
              case ConnectionState.waiting: 
              return StateNone();
              break;
              case ConnectionState.done: 
                Map<String, dynamic> json = jsonDecode(snapshot.data);
                //print(json);
                  var data = Autogenerated.fromJson(json);
                  if (data.m == 'success'){
                    dynamic categoryList = data.d.categoryList;
                    
                    categoryList.forEach((li){
                        tabContent.add(
                          listContent(li),
                        );
                        tabs.add(new Tab(
                          text: li.name,
                        ));
                    });
                    return IndexedStack(
                      index: 0,
                      children: <Widget>[
                        DefaultTabController(
                          length: tabs.length,
                          child: Scaffold(
                            appBar: AppBar(
                              title: Text("掘金",style: TextStyle(color: Colors.white)),
                              bottom: TabBar(
                                tabs: tabs,
                                indicatorSize:TabBarIndicatorSize.label,
                                isScrollable: true,
                              ),
                            ),
                            body: new TabBarView(
                              children: tabContent,
                            )
                          ),
                        ),
                       
                      ],
                    );
                  } else {
                    return StateNone();
                  }
                
                break;
              
              case ConnectionState.active:
                // TODO: Handle this case.
                break;
            }
            return null;
          },
    );
  }
}
// first Page 
 

// 构建未获取数据渲染界面
class StateNone extends StatefulWidget {
  @override
  _StateNoneState createState() => _StateNoneState();
}

class _StateNoneState extends State<StateNone> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('掘金'),
      ),
      body: Center(child: Text('加载中'),),
    );
  }
}



